import './globals.css';
import type { Metadata } from 'next';
import { Inter, Saira_Semi_Condensed } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });
const SairaSemiCondensed = Saira_Semi_Condensed({
  subsets: ['latin'],
  weight: '300',
  variable: '--ssc',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Sustainable Manufacturing Toolkit',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`${SairaSemiCondensed.variable} `}>
      <body className='bg-gray-600 flex flex-col h-screen'>
        <Navbar />
        <div className='flex-grow'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
